contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://mborgia.github.io/test-hugo"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true
